version: "3.8"
services:
  app:
    build: .
    ports: ["8080:8080"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on: [postgres, redis]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: Example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localSQL
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]
